# Generated by Django 4.2.4 on 2023-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0002_sustainablefarmingpractice_transaction_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='agritoken_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
