# Generated by Django 4.2.4 on 2023-08-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0004_alter_loanapplication_status_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='agritoken_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
